### ISSUE TITLE
Flash fallback does not work in IE & poster image is buggy

### ISSUE THREAD

**Issue by DuaneTravis** [jgallen23/videojs-playLists#5]
1) In the regular VideoJS there is a Flash fallback for IE and all browsers if you only want to use mp4. In IE8 none of the videos display as the do in the regular standard one video player.
2) Also, if I only link to an MP4 (don't want to have to support OGV and WebM) the poster image doesn't display. For some reason if I like to an MP4 and an OGV the poster works, but not only an MP4.

Thank you and great playlist.

**Comment by Antonio-Laguna** [comment]
I've reviewed the mp4 issue and I can't replicate. Maybe it's only an IE8 issue which I won't give support for given the fact that is currently 3 versions behind the actual version of IE.

However, I've tested and with the latest build and it seems to be fixed on IE8
