### ISSUE TITLE
Not compatible with videojs 4.2.2

### ISSUE THREAD

**Issue by ghost** [jgallen23/videojs-playLists#6]
Hello Belelros,

First of all thanks for the plugin. I'm planning on using it.

However, while testing the plugin with videojs I ran into the error that `player.pl.el` didn't exist. Looking into the code it looks like
[line 34 of lib/videojs-playlists.js](https://github.com/Belelros/videojs-playLists/blob/master/lib/videojs-playlists.js#L34) `var parent = player.pl.el.parentNode,` is where it's throwing the error and
[line 22](https://github.com/Belelros/videojs-playLists/blob/master/lib/videojs-playlists.js#L22) `player.pl.el = player.N;` is the root cause.

It seems like we're trying to access an attribute after the code is minified and it might change depending on who minifies videojs.
I'm not sure how this should be solved, but I think it would involve sending a pull-request with changes to videojs/video-js/src/js/player.js creating a getter-method for the player element.

Cheers

**Comment by Antonio-Laguna** [comment]
Hi there!

Thank you for noticing that. I noticed some days ago while I was doing some work for a client. It didn't work and thought exactly the same as you. As soon as I find time to solve this, I will. The suggestion you make is the approach I thought as well so I'll get my hands dirty!

I'll let you know closing this.

**Comment by pixelsucht** [comment]
Any news on that? I'm having the same problem. Thank you.

**Comment by Antonio-Laguna** [comment]
I tried to add it into the code, it seems there is another solution but it's not documented by them... Have to open a ticket to them
