### ISSUE TITLE
Not working with 4.3

### ISSUE THREAD

**Issue by cannycookie** [jgallen23/videojs-playLists#9]
Hey man, 

Thank you for this, will be really useful - I hope!

Looks like the same issue as #6 
Uncaught TypeError: Cannot read property 'parentNode' of undefined 

I'm not good enough to work out what is happening, any idea?

**Comment by Antonio-Laguna** [comment]
This issue has been solved, the Demo now shows it working with 4.3

**Comment by cannycookie** [comment]
Yay! Thank you so much.  Really appreciate the effort. :-)
